version: "3"
services:
  workspace:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace
    tty: true

  api:
    build:
      dockerfile: ./api/Dockerfile
    volumes:
       - ./api:/app/
    expose:
      - 8000
    ports:
      - 8000:8000 # Host Port: Container Port
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
