version: "3"
services:
  workspace:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
       - ./api:/app/
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./api/.env
  
  slack:
    build:
      context: ./slack
      dockerfile: Dockerfile
    volumes:
       - ./slack:/app/
    ports:
      - 8800:8800
    command: uvicorn bot:fastapi_app --reload --host 0.0.0.0 --port 8800
    env_file:
      - ./slack/.env


